server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_ocean?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Zx123456
  redis:
    host: 127.0.0.1
    port: 6379


mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    personal:
      zx:
        myocean:
          mapper: trace

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default