spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisplusdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zx123456
  application:
    name: mybatis-puls
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

server:
  port: 8888

